name: cloudflared

image:
  repository: cloudflare/cloudflared
  pullPolicy: Always
  tag: latest

port: 80

resources:
  min:
    cpu: 100m
    memory: 128Mi
  max:
    cpu: 500m
    memory: 256Mi
  autoscaling:
    enable: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

health:
  liveness:
    enabled: false
  readiness:
    enabled: false

env:

secrets:
  - name: TOKEN
    secret: cloudflared-secret
    key: token

args:
  - tunnel
  - --no-autoupdate
  - run
  - --token
  - $(TOKEN)

ingress:
  enabled: false
