name: sealed-secrets
repoURL: https://bitnami-labs.github.io/sealed-secrets
targetRevision: 2.17.2
chart: sealed-secrets
namespace: infra
values: |
  fullnameOverride: sealed-secrets
  namespaceOverride: sealed-secrets
