apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
        name: cloudflare
    spec:
      containers:
        - name: cloudflare
          image: cloudflare/cloudflared:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-secret
                  key: token
          volumeMounts:
            - name: cloudflare-cert-volume
              mountPath: /etc/cloudflared/cert
              readOnly: true
          args:
            - "tunnel"
            - "--no-autoupdate"
            - "run"
            - "--token"
            - "$(TOKEN)"
            - "--origin-ca-pool"
            - "/etc/cloudflared/cert/tls.crt"  # Apontando diretamente para o arquivo do certificado no Secret
      volumes:
        - name: cloudflare-cert-volume
          secret:
            secretName: cert-tls  # Nome do seu segredo
            items:
              - key: tls.crt  # O campo que contém o certificado no segredo
                path: tls.crt  # Nome do arquivo que será montado
