name: nextcloud
repoURL: https://nextcloud.github.io/helm/
targetRevision: 7.0.4
chart: nextcloud
namespace: nextcloud
values: |
    nextcloud:
        host: drive.flyfood.com.br
        trustedDomains:
            - drive.flyfood.com.br
    service:
        port: 80
    ingress:
        enabled: true
        className: traefik
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - drive.flyfood.com.br
            secretName: cert-tls
    persistence:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 10Gi
        nextcloudData:
            enabled: true
            storageClass: "longhorn"
            accessMode: ReadWriteOnce
            size: 200Gi
        


