apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/oprimogus/flyfood-gitops.git
        revision: HEAD
        directories:
          - path: "k8s/**/prd"
  template:
    metadata:
      name: '{{path.components[1]}}-{{path.components[2]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/oprimogus/flyfood-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.components[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
