apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-secret
  namespace: cert-manager
spec:
  encryptedData:
    dns-api-token: AgB0OQurbKTOBU0dXqBvGaQuHMbsAbGGzWP0ClKC1m/mmqunQbDjk9zjqTDw89DPFImZNP1E8zoEQIawVQK2zz9MqKw3CPkcprHUFd/c7CkHXi9MOQDY+ymDhwpAo3Far358gyOkRJK5hTNdWKWq4qUUTBTSsLMiD/BvjjKYYDQdcC3at4Q4Dy5SoPOM+JDK1yYmp/QtMUePpwQoLCj0SHDTsJMuAj6hPQorEY5B1N56E+jIJXHCe3dINZxI7m+jBhS2VC39FpyZ3sGD+EK83E6gEnjXMkBytxVjxkgGn14rGDkpeTSQCvdW/oaHisg11OAb0j7TSht8EZOpoBcpC/UNOmaFSf0L40a0x5x4rUEUOUcx2rXZGbeykvT9l4T8QPconU5ZOUQyHQRmKke1yBGHWNiIPUA38GAskNks+MHkJvLDheOnHjRuPmxb3RF82zm6FnhP5f7IWFjoYC+3bMRxm4JcPMPzEaJyE8li+hoz+qgUB/S68+IYF4aLB8vyoU16unZAWBB/SCYeR4LaqtztAPhQhxTVT2GqVG9ZS7wQfCSCpABIXhg5CRy2DJooAiMe6+8UnRFSEEhPMUhfn4MgA+QrtX9v4ZWnvUMCeRZ78/kbvNnrJE0EGGPQvDEe3hReUAFthiBbcajuaEIWX7kv6C7LLzhDlx7nWPl4jC/dAXncd7JAK9EARU5z2CLvdzvi17EnHRzLIMw2xjNte8N7hd96f6DXKiVMm23tI0Wc+zuuItFXzDup
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-secret
      namespace: cert-manager
    type: Opaque

