apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flyfood-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgCOT/7dMSdeQK5QWnQith+gRr/j4tpk1FNTiBO4wLCvZzMKF+3v0LObAXcF86cCTjhHa7I5LER2pzz1SOm3Ma0lgHk+d1DD8Sa6ZR8Df9lotpEdMaxB6rzb/MzC+WPtw91hYj7exyU4XwS74HROW2SJs8nXII6gBc9ReKx8M7k3RMeCYUMyjaet9hYpZlqAgczCHkD5VgHgs7LZxmRpHI1qmxY4ntBXQTPe0WA1Q/cBRCAMmf/ESR76vrG/NnqjhI+BR3q6xu6XWRV4SIzs77V+ffDrLE+xqbO2jDYpW7eGpnkF1VJk3qQgmMh9eh4WNfm1zzlOVyXhGKbcqn+gSgb6IoOn5/R8bdqjPCx5KlyJwehqF6Vi85W6kTrAx64m8pxFZiQNrNY9aXHACghN+oCwsZFcusxPJO3oshK+r8/QNFJZk8CeWjgGRBLJWCCrcGi615iaXOviaEiuzFhYQhgGdmKEafOfoe95VhPVxWlcQhC2/zrC9P8kAKrsi+PDTPqjLC7OBXJTD3yUvf2p7PTBRNj6qdZi9Zo8G9/msGO0wS5DZRQIAmxqS6cK/tbIJSoxFuWw48DSSPy3fw4kTEKGOQRKZv4cfDxgVaT8ecSOBBAjCUJdwzXq4HdAC3pkwM76Y5ZqULmT/lGSr7vRnk6jCXPFEtIjBtJat4rfbS1s5gfgJWMLFSTQqDAyrObOxyasimdh9287xmBtrXD/wQZD0Jof6oEGJOdBrvgpfwFKMwWPBMfKdmU1
    username: AgA9VFN70VaSIpqwW/NQTiqDfxFDHPx+kaHk6QVRdtpQ5G5s3Y/Dv4el0AseHO4uNh/HncUvTNn4+fD0yGvtkfzDtWR4PX3YFbXf4qw7oCwTiGlQuLb85pTZXO7xbApXY5i8ilBtZwDN0QmSqrvA2qOwBsXUI7haVZnGFoxH6DYIe3rqns8tveKFbXqGvpn8qgTCTyu6/OyjBvumx1diM66bzQT6T93/WNxJeQrnvSrA51I8N7glD/O9s723p+7XsRyHxN+Ve/asfilbfJP9o/YrNjNyVbfU7+xh0jQ84nR2XdKsRy48NzeFpASOyZz94eUrO/G6Vy+F+9x4XW9PXNmo1awCfwQMhePVx0SRDxC+MiWOz9waMAkEt4KmcCPZfQY6rK+Wt+cvroOlm1J7KsvP4oqXBvgiU++ZjLTgCnqQARdbsOO2eR4HovmAvTI4WIo0rrrjrKGFwgEXyHcfXGHxHIXJckorUh2TawhWCPusmljZ/70/0Bv4JoRyRzcJ4vo8LJTokjRnkPoMl7Q+CQ4h/CDxaGLZAIUJUBSoCa7uKS7iWYKQAfDzXf91s6p1QhlNxfahv5jxteYaEni0pBjPMP0QdUIt59M5IZKLTi3pKHb/CEx8s49/CKZlJzsamydWrx0EbOMbAw7afTm2xoafEjsNA6aDHFqvrJk+Z/Tlr1q3ljqZLQA3lYdJpxI2Out+moDIK5QXIlfYYA==
  template:
    metadata:
      creationTimestamp: null
      name: flyfood-db-secret
      namespace: postgres-cluster
    type: kubernetes.io/basic-auth

