apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flyfood-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgA3PFGYURmYfTE5GxGDbNegizw7MnmRrc4Lgz+xhDVmFjc/vwTeLdLt1W2viXE25GfWdRiPkIhR14zj8IcBXWyszzfMFkplaRq3EJyfan8TDO3c+CxSNeHLLFeePie8UyYHkcwtFyFuLXINa+Fo6c/W8xPws6LpZNTG3TF01Mhm0tHK3MmCahWQtD28ekaot722Q3I2bLPcm1XrRhGSzvIFaRUHVyIMTvKSLXg/kUJv6F0Ge1BmC7yW2gOmfTi44xgxSNfxy1aHRL0MXLii4O62JD9Wt7mPm12qSwK5ytKkGLpE3Cw9pki1ucG9HLLXrRS603rjtCF2S3xy+U0bZlHxDMtrhHPwpKX/dYJdDiQ39p3wdg5nG7fjj/410zAoXuWC5iechY2g8L/5cckFDUUucOsdbkQeHoSno+3h+AcQIdoSRmZK3ymy08WD/3Pw0Gt/EEO9RhdtXI1RUxGhqkl9rKT+63/pG2y6Bau9A4823+hbpg/+YQfoCMfw1PYzZUxh2Or8dDudFd/RNH+2sFVbs9YFNLWnpdLLie7UxXOgXVhKJZE5+npILf/BMumEVMaFd5UXmDq/Z8gXSW4IDWNKpK3u8+oqA2T1tPuWKmbtXUBuuxI9gqftNyKhZXo/8w9hCzyFNSA1KEgdpuvgRgGyx/sjSHNgdB7R0WrBozfRz5Hnci5B38SbQuqEJjDbiBNGd8c6GuuBBevvqzIzY0tdFHMdQE2InAIu180z7NhRWOFC
    username: AgCtkPTy2Ap2y+Cr9FAwxLOMSn4+hwtO1/LBWSjxI9tAkp7OwXi3+ubxtuJwjqd6UPRV0Fr+Mvn+hhRfAFj1rDKqEha7hkk5RaJFJecVS1meY9u2NuWsGGUCwaVSUBJjq7cVCpVj1V2WiP5DCAEF+fM9+Yg4D3iN4qTr/SLA+yLQ6UDEwFqFGvf0Q8dvD/1Uj9P2u1MuOATfDiUuMIqsFxkGUonEC84u34iKp8GZfKK5Ze9m785EDKMuSv/7M5OA6XN351PH/OugmZoxPPn+d59QIrVtarbHBwHRkLzt5aJb3ljEcVlwpS5D+rqn80INy8Vt8rTJbaolNscm9fcVYLGicHr3pes0SJ814GwQnBeJp61B8aH4WtuXDG/wZC9tafYIPAPW+7XhOkDd3AGaGiy8RcB68r4HqWhBypBm1ZcT3udA8aXzrpj6Zlf6Ir2lc9tFCptKPMV8zOIY+ZLgb3EURCsN6ortldfU3usz6sSHwuG8goQP2xl1aDFqBmsTG9gddtH/blJqlCcFhmpwoxSh67bsGAtOm5nkvicFxEMvRdJV2Aue7xTR5t6RGCt2TbxytdggnVg+/Rlu/waFxV6abGoyv4vFe8UH5PJhh41p8Sl5d4qMng46W5f6qrAW2S/ARkHCSAEpm3UzLGY0Ylr1S9p///6927mKcbisXcgmtPo9H1NaixKbi/APMkGmu6QUmDgT855lFEzqSA==
  template:
    metadata:
      creationTimestamp: null
      name: flyfood-db-secret
      namespace: default
    type: kubernetes.io/basic-auth

