apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prd-flyfood-db-secret
  namespace: infra
spec:
  encryptedData:
    password: AgDk6YXYT+A0f+PijTsmJff7mkR5USM8etqGLCQRr1VfifjEKIROFFZeMpTenF3LanlwWpFgIia8jUYiGKFW22yk1BAZgr2q66Y6PTqac+mWllnrDG8lwtRR7staS+gvSI/gryyUz1VHy7DqGG1eaeAUQsYXvnJljs6HgISJbTwPc8jyxuhL9qYTnsRuouvUbHtiAkG0iXJgnmLSzjIUS1O5JzH8zZq2nhv4ywuDrnVgqOC6irWd5F38uDICHaKGxZQxhLjU8w+ef+ip0HG05JvbQHDypqsTkax8x4pJQkk02019DEp87J3p1Bxk660zp+zKny/HatoXg2R2vZ2X7EVGKkyWnnu7jP2BTJlv3IJk4iUvcpBt7r9J1sNEWXfZoYMMge7q8HQvG54xtZ2IAffWfLbD6Px6nUnHuluB6HJY86HENCrI3FWJbxxl08jYHxGRSg2fv002iQbfkrOG0aFbhvvWYyOA3kXIfsU4SWBQsVPXGEfOCwnF5ET64xbOld/h2F+Ci6ARLSTlpbM/v1ltFPKCaBku9SpzCw7zL/8fLxoCJP/TaQ1Jz1kTAGLByQVSpIjP0oFlEFgLTbwTSC0Of6421TCdGH/5d6sf07vl/8Ll54J5NF57oxZ1SCssgHlQY9dcJOph7sihtc5F1f/FGGL/55kSWfteX0IFIDE0bO2IJTdfvv9nXQmgxzMvEzB6mGyR+GWxM6W6lQ9FVCrfCo1yS3ci1qcYzXB7o60PZqLxzAPx
    username: AgDefDfAR71FwBTemxSPT3HBjgpktVv/BxIe8J1HgdWDs6DasdzhW2VV92QDD90/vmKfxKYW8Jr5WKjYPXADoPwHKvw5cIen7P4vk0A00QBVAl0wzyAksX0Uva862X5n5DB4Ei5Wzcr7xnC3vZCFOrjSyYBbGqmyg+lI/lifqMdMo34X7PckAXkvNpW4Qhl+nLllOhAXTsdPFQMOMml+sqX0tdrxtv4loqdAPH8C7/rnHRx5QZtRU+lhVx8u1Qgag2VcbO/yiFXEWkLMf3jkZS1SEhE3ABCGQ4sBbISwXNsKiwrIyRL4a1cc7fIBK+xwoqbT43570KpRxal5Y71/ysKfGHrIhSrqtPGFDCWPstwZ0QlOqeNi5BGzOA09o25+8hAf6LOZLmSpFk8xvCq8MmZkCkBSkygf7z39oSdBImSdRs6rasZZP3KaEWdZEXjLhXJtC2GyhtZE5or8cZ2SoK14sPD+vDxjKqiZ7hHWpQ7XmrrRpP7fkq2Mk10BwGT23GzOS/x7HEhD/sObaYTf1OBDMMwAVI9dtEQuckpQW5pWHVY0Ym7T174x/ikMDgg0q4iPbYRJjePNT8iMgNanrqilxEMBxSNkt8H6qvXdOFnQAsMQaDoko724/fmVCbDcgdwCmlnl/gfanp7b6zHOB7oqdgv1CKWQkvpUasLRxGCIVyO4asU9kvovvZz/yKcP6IkOkOFg6odt5R7dhw==
  template:
    metadata:
      creationTimestamp: null
      name: prd-flyfood-db-secret
      namespace: infra
    type: kubernetes.io/basic-auth

