apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dev-flyfood-db-secret
  namespace: infra
spec:
  encryptedData:
    password: AgCbLHgzTG4HjBVmNOKakTOD0YNvEC5i7eT4fVQn4i5f50ji7EsW38YjgF5NKaIViQi2ZnBpJDq4GUa4i9eZ5JvYAVAGjfUcnsqnmD9aGgVbroO66xmQ/xbrAJ4JUQP+o3QCPk+umOxBOvO/CG7lb5Er2kQVunr3Ny8tWpFRq1/W1vd5h2B42PAadlqciBqK1qb3BmeDp6HTQXofTdoSrZIM2XTiqAcoPqGIKhwVJ5G9GCYldlyqJYHC33RP/FFDSpagjnHRbHh94wbHHPzeVPzMcUlEwV0/JiNI2ukeSSmPT5xa2M9SoR8BTXVHlQgQG0jsy2fGZvpdmiDEkZjRT9o6YILRUKu2yL2i90ekLptOmbx5ifCGv/0hekf7yGK7GJ5zoydsJYFwBodbnRpnd0AMTMSQ63fZI3qPalLHZnfhB7Zof5B7j0mIKmH/PmGDtaydWNHDfZe9rhkkzEEFFSMCtdM2EGgeAiW/eXUzJpjv+EQnlE+fvm693uUalU7JQQqdqdeHZjDrHlbGBk3MSnkdAS8Wl6lsA5SVsBGAt7p05lkAYn+vkJZlVCZ18SkfDtb0+aoA12YUGjTyU3HzAoBx0WveYUX1Wh5qa36uGwnSUHiEYiDbzwTsmdmI1I2Ch20Sp5KCuAUmIWFVxVZBVqPET+BYEgI2EtUByFcDDXBTLbTswPBYMFjXj9MDw2rdDT5C/ljOHpfnatDw+oVEAibCu113obKZAvmipy+GJpQmGPU=
    username: AgCtozAQw7mkAVyjIiwQyQiEqszJepcGv0SSpNZRxkEqdCIjOr5Ig7oZivKWqByePFg5fqoYvPNZ1iJ+Ejh9rQ27UatYKLXf0FDFAivw8n17b0E59mtrdOLLOYJcR2zsYc4F+TL1iuEHWG0CWeJQQ3j9H+kU/teEAPKeAR7k3FUttOXktZtiFWo63k7tu+yjEPpP47RbTpRVCEZqRP5gkR6dPGTPXFA/DTJVlQ2zbZRW+zvqpSSvCWWbU5UswAKQmlA43JnwNg1hCCLixwBtEi4+w3jk2btXWrXV/7hd0E8Z1SbZDsm/ewYFNwk+07gcxMolvyR7Qs2YJEHyN786WsSTz8ZXCrzBx4ld0RFA157YydfQyZaFczC4/XB1F5Xu9vsyHeaM6jwBbyazXQOLG4xGf3h/cR+VMDppWgfrG5LpDTvbFCvc936ONfwxQ/Lu97/ZArxKS+zMu0j4xrQVgCHIIM9FURbQkuMEc2DXQxuIo5y7K/WWdE6YNORCrcrYLjvSRGB9OlqRuhhlYJK7UlzUXTPhAltH/kANenfLJUvsF0RzCEjBbnnPz5YDZSd379U912zm0FtSaxvn4AED+2eGiYwsvPuXJu6vZMPzZjbjKdBEL0J1OdCz2E78f16SiT1YVULStLLTuxiBjKithCNHqPe9COV/qVHnhpZZsReCwRZJRBUH9IqEpeGZVW4wh6oc2y06dL1EJlAk9zEHU6M=
  template:
    metadata:
      creationTimestamp: null
      name: dev-flyfood-db-secret
      namespace: infra
    type: kubernetes.io/basic-auth

