apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-secret
  namespace: infra
spec:
  encryptedData:
    token: AgDepgla38j+qSjlblrSWwH4s1sC7AZwsv/HddHNyDmo1cpMb6X/3RZzgqayV4DoWKJ1XfA5bfkixuK2lhCI53/6qkFtZlQh1gcFR6OdvwiJO8hDIyfLJ3IeOWc2TAPTM8iZL53XrITPJvPDENrgz7f2SGxdDhUB4ZLCMTNorEYR8f8GN+6bjvxt8MNXFSNrLfY9TFvJJLPYZK6QGWubkT9E1Nq/nKOxwuBW1nfWTIqr8KfZ2AxZM75Jnlgyfe9bifLh8gP9PecqdgKpaSL4eyycGta3dN9EeLllIXUS8f5Gns3q53JMoTb3mxYr5WHwfdMmSl5f+gnDFs2JFik8N+1YPUEMePLTurYI6wh4LSZhB5AnmzXvM5lSwpL2HD1lQz88CUePBKCZ8vdvsj+7GsFPL5gphrNGQDVogmGAOLbkrZyprzCpEYtswfF7SV+dl7u9eDenO9eTtOoeqG00LlJK2qFOP/ZJ9RnhurGf2SUJkIRkFslH48jTO24ig4jQYLKuoCF/83RNdP2YCUvgf81nMynAUvQtbJu8zVrN5a51EeyZHC0HliTa3XptRg5RUtLKSF0oi/xSomGN6qDfaHesuOGgIGUbbaaw/6rGpbslYaAQ/T2jonSsij/Wy3tIo52NNDPaxgtTtrXRFhdhz0Pk3yiNjnX/B0LPgAUAD63v3Xpt9Z8yQhr9obJvhdHm++KIA8Qyn1S0EbDQBZzubwroAx5Hn6m4V1y6Nh3D
  template:
    metadata:
      creationTimestamp: null
      name: vault-secret
      namespace: infra
    type: Opaque

