# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: outro-prd
#   labels:
#     app: outro-prd
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: outro-prd
#   template:
#     metadata:
#       labels:
#         app: outro-prd
#     spec:
#       containers:
#         - name: outro-prd
#           image: nginxdemos/hello:latest
#           ports:
#             - containerPort: 80
#           env:
#             - name: ENVIRONMENT
#               value: "production"
            
#             - name: API_PORT
#               value: "3000"
            
#             - name: API_SERVICE_NAME
#               value: "flyfood-api"
