name: flyfood-web
environment: dev
port: 3000

annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll      
    keel.sh/pollSchedule: "@every 30s"

image:
  repository: ghcr.io/oprimogus/flyfood-web
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - ghcr-secret

resources:
  min:
    cpu: 100m
    memory: 128Mi
  max:
    cpu: 500m
    memory: 256Mi
  autoscaling:
    enable: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

health:
  liveness:
    enabled: true
  readiness:
    enabled: true

env:
  NODE_ENV: production

  CLIENT_FLYFOOD_API: https://flyfood.com.br/api
  CLIENT_VIACEP_API: http://viacep.com.br

  AUTH_ZITADEL_ISSUER: auth.flyfood.com.br
  AUTH_ZITADEL_ID: 316869047071342604

secrets:

ingress:
  enabled: true
  host: dev.flyfood.com.br
  path: /
