name: flyfood-web
environment: prd
port: 3000

annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll      
    keel.sh/pollSchedule: "@every 30s"

image:
  repository: ghcr.io/oprimogus/flyfood-web
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - ghcr-secret

resources:
  min:
    cpu: 100m
    memory: 128Mi
  max:
    cpu: 500m
    memory: 256Mi
  autoscaling:
    enable: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

health:
  liveness:
    enabled: true
  readiness:
    enabled: true

env:
  NODE_ENV: production

  CLIENT_FLYFOOD_API: https://flyfood.com.br/flyfood-api
  CLIENT_VIACEP_API: http://viacep.com.br

  NEXTAUTH_URL: https://flyfood.com.br
  AUTH_ZITADEL_ISSUER: https://auth.flyfood.com.br
  AUTH_ZITADEL_ID: "317736390097960989"
  AUTH_ZITADEL_PROJECT_ID: "317736215765843998"
  AUTH_TRUST_HOST: true

secrets:
  - name: AUTH_SECRET
    secret: prd-flyfood-web
    key: AUTH_SECRET

ingress:
  enabled: true
  host: flyfood.com.br
  path: /
