# infrastructure/postgres-operator/argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crunchy-postgres-operator
spec:
  project: default
  source:
    repoURL: https://charts.crunchydata.com/
    chart: pgo
    targetRevision: 5.4.2
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
