apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: longhorn
    size: 40Gi
  monitoring:
    enablePodMonitor: true