name: flyfood-api
environment: dev

image:
  repository: ghcr.io/oprimogus/flyfood-api
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - ghcr-secret

port: 3000

resources:
  min:
    cpu: 100m
    memory: 128Mi
  max:
    cpu: 500m
    memory: 256Mi
  autoscaling:
    enable: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

health:
  liveness:
    enabled: true
  readiness:
    enabled: true

env:
  DB_HOST: postgres-cluster-rw.infra.svc.cluster.local
  DB_PORT: 5432

  API_PORT: 3000
  API_SERVICE_NAME: flyfood-api
  API_BASE_PATH: /flyfood-api
  ENVIRONMENT: production
  SQLCDEBUG: 0

  ZITADEL_ISSUER: https://zitadel.infra.svc.cluster.local
  ZITADEL_DOMAIN: auth.flyfood.com.br
  ZITADEL_PORT: 443
  ZITADEL_KEY: /key.json
  ZITADEL_SERVICE_ACCOUNT_KEY: /service-account-key.json

secrets:
  - name: DB_NAME
    secret: flyfood-db-secret
    key: DB_NAME
  
  - name: DB_USERNAME
    secret: flyfood-db-secret
    key: DB_USERNAME

  - name: DB_PASSWORD
    secret: flyfood-db-secret
    key: DB_PASSWORD  

  - name: ZITADEL_PROJECT_ID
    secret: dev-flyfood-zitadel
    key: project-id

  - name: ZITADEL_CLIENT_ID
    secret: dev-flyfood-zitadel
    key: client-id

  - name: ZITADEL_KEY
    secret: dev-flyfood-zitadel
    key: key
    mountPath: /key.json

  - name: ZITADEL_SERVICE_ACCOUNT_KEY
    secret: dev-flyfood-zitadel
    key: service-account-key
    mountPath: /service-account-key.json

ingress:
  enabled: true
  host: dev.flyfood.com.br
  path: /flyfood-api
