apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
spec:
  secretName: vault-cert
  dnsNames:
    - vault
    - vault.infra
    - vault.infra.svc
    - hashicorp-vault.infra.svc
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
