apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca
  namespace: infra
spec:
  isCA: true
  commonName: internal-ca
  secretName: internal-ca-secret
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
