name: jellyfin
repoURL: https://utkuozdemir.org/helm-charts
targetRevision: 2.0.0
chart: jellyfin
namespace: jellyfin
values: |
    persistence:
      config:
        enabled: true
        isPvc: true
        storageClass: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 2Gi
    
      data:
        enabled: true
        isPvc: true
        storageClass: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 500Gi

