name: jellyfin
repoURL: https://utkuozdemir.org/helm-charts
targetRevision: 2.0.0
chart: jellyfin
namespace: jellyfin
values: |
    image:
        repository: jellyfin/jellyfin
        tag: "2025090105"
        pullPolicy: IfNotPresent
    persistence:
      config:
        enabled: true
        isPvc: true
        storageClass: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 2Gi
    
      data:
        enabled: true
        isPvc: true
        storageClass: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 500Gi
        
    hostNetwork: true
    port: 8096
    hostPort:
        enabled: true
        port: 8096

