name: pg-cluster
repoURL: https://cloudnative-pg.github.io/charts
targetRevision: 0.23.2
chart: cluster
namespace: database
values: |
  # Configurações do cluster PostgreSQL
  cluster:
    instances: 3
    enableSuperuserAccess: true
    storage:
      size: 10Gi
  # Você pode adicionar configurações adicionais conforme necessário
  # Por exemplo:
  # backup:
  #   retentionPolicy: 30d
  # resources:
  #   requests:
  #     cpu: 200m
  #     memory: 512Mi