apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-application.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "generic-application.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.port }}
