name: zitadel
repoURL: 'https://charts.zitadel.com'
targetRevision: 8.13.1
chart: zitadel
namespace: infra
values: |
  zitadel:
    initContainers: []
    masterkeySecretName: zitadel-masterkey-secret
    debug:
      enabled: true
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "1"
      initContainers: []
      extraContainers: []
    configmapConfig:
      ExternalSecure: true
      ExternalDomain: zitadel.flyfood.com.br
      TLS:
        Enabled: true
      Database:
        Postgres:
          Host: postgres-cluster-rw.infra.svc.cluster.local
          Port: 5432
          Database: zitadel-db
          MaxOpenConns: 20
          MaxIdleConns: 10
          MaxConnLifetime: 30m
          MaxConnIdleTime: 5m
    secretConfig:
      Database:
        Postgres:
          User:
            Username:
              valueFrom:
                secretKeyRef:
                  name: zitadel-vars-secret
                  key: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
            Password:
              valueFrom:
                secretKeyRef:
                  name: zitadel-vars-secret
                  key: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD

    dbSslCaCrtSecret: internal-ca-secret
    dbSslAdminCrtSecret: postgres-cluster-client-cert
    dbSslUserCrtSecret: postgres-cluster-client-cert
