name: zitadel
repoURL: 'https://charts.zitadel.com'
targetRevision: 8.13.1
chart: zitadel
namespace: infra
values: |
  envVarsSecret: zitadel-vars-secret
  zitadel:
    initContainers: []
    masterkeySecretName: zitadel-masterkey-secret
    debug:
      enabled: true
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "1"
      initContainers: []
      extraContainers: []
    configmapConfig:
      ExternalSecure: true
      ExternalDomain: flyfood.com.br
      ExternalPort: 443
      ExternalPrefix: /zitadel
      TLS:
        Enabled: true
      Database:
        Postgres:
          Host: postgres-cluster-rw.infra.svc.cluster.local
          Port: 5432
          Database: zitadel-db
          MaxOpenConns: 20
          MaxIdleConns: 10
          MaxConnLifetime: 30m
          MaxConnIdleTime: 5m
          User:
            Username: zitadel
            SSL:
              Mode: verify-full
          Admin:
            Username: zitadel
            SSL:
              Mode: verify-full
    dbSslCaCrtSecret: internal-ca-secret
    dbSslAdminCrtSecret: postgres-cluster-client-cert
    dbSslUserCrtSecret: postgres-cluster-client-cert
    serverSslCrtSecret: cert-tls
  ingress:
    enabled: true
    className: "traefik"
    annotations: {}
    hosts:
      - host: flyfood.com.br
        paths:
          - path: /zitadel
            pathType: Prefix
    tls:
      - hosts: 
          - flyfood.com.br
        secretName: cert-tls
