name: zitadel
repoURL: 'https://charts.zitadel.com'
targetRevision: 8.13.1
chart: zitadel
namespace: infra
values: |
  zitadel:
    initContainers: []
    masterkeySecretName: zitadel-masterkey-secret
    envVarsSecret: zitadel-vars-secrets
    configmapConfig:
      ExternalSecure: true
      ExternalDomain: zitadel.flyfood.com.br
      TLS:
        Enabled: true
      Database:
        Postgres:
          Host: postgres-cluster-rw.infra.svc.cluster.local
          Port: 5432
          Database: zitadel-db
          MaxOpenConns: 20
          MaxIdleConns: 10
          MaxConnLifetime: 30m
          MaxConnIdleTime: 5m
          User:
            Username: zitadel
            SSL:
              Mode: verify-full
          Admin:
            Username: postgres
            SSL:
              Mode: verify-full
    env:
      - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
      - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_EXISTINGDATABASE
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_ADMIN_EXISTINGDATABASE
      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD

    dbSslCaCrtSecret: internal-ca-secret
    dbSslAdminCrtSecret: postgres-cluster-client-cert
    dbSslUserCrtSecret: postgres-cluster-client-cert
