name: zitadel
repoURL: 'https://charts.zitadel.com'
targetRevision: 8.13.1
chart: zitadel
namespace: infra
values: |
  zitadel:
    initContainers: []
    masterkeySecretName: zitadel-masterkey-secret
    envVarsSecret: zitadel-vars-secret
    configmapConfig:
      ExternalSecure: true
      ExternalDomain: zitadel.flyfood.com.br
      TLS:
        Enabled: true
    dbSslCaCrtSecret: internal-ca-secret
    dbSslAdminCrtSecret: postgres-cluster-client-cert
    dbSslUserCrtSecret: postgres-cluster-client-cert
