name: zitadel
repoURL: 'https://charts.zitadel.com'
targetRevision: 8.13.1
chart: zitadel
namespace: infra
values: |
  envVarsSecret: zitadel-vars-secret
  zitadel:
    initContainers: []
    masterkeySecretName: zitadel-masterkey-secret
    debug:
      enabled: true
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "1"
      initContainers: []
      extraContainers: []
    configmapConfig:
      ExternalSecure: true
      ExternalDomain: zitadel.flyfood.com.br
      TLS:
        Enabled: true
      Database:
        Postgres:
          Host: postgres-cluster-rw.infra.svc.cluster.local
          Port: 5432
          Database: zitadel-db
          MaxOpenConns: 20
          MaxIdleConns: 10
          MaxConnLifetime: 30m
          MaxConnIdleTime: 5m
          User:
            Username: zitadel
            SSL:
              Mode: verify-full
          Admin:
            Username: zitadel
            SSL:
              Mode: verify-full
    dbSslCaCrtSecret: internal-ca-secret
    dbSslAdminCrtSecret: postgres-cluster-client-cert
    dbSslUserCrtSecret: postgres-cluster-client-cert
    serverSslCrtSecret: cert-tls
    ingress:
      enabled: false
      className: "traefik"
      annotations: {}
      hosts:
        - host: zitadel.flyfood.com.br
          paths:
            - path: /
              pathType: Prefix
      tls:
        - host: zitadel.flyfood.com.br
        secretName: cert-tls
