name: zitadel
repoURL: 'https://charts.zitadel.com'
targetRevision: 8.13.1
chart: zitadel
namespace: infra
values: |
  zitadel:
    initContainers: []
    masterkeySecretName: zitadel-masterkey-secret
    configmapConfig:
      ExternalSecure: true
      ExternalDomain: zitadel.flyfood.com.br
      TLS:
        Enabled: true
    env:
      - name: ZITADEL_DATABASE_POSTGRES_HOST
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_HOST
      
      - name: ZITADEL_DATABASE_POSTGRES_PORT
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_PORT

      - name: ZITADEL_DATABASE_POSTGRES_DATABASE
        value: 5432
      
      - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_USER_USERNAME

      - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD

      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_EXISTINGDATABASE
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_ADMIN_EXISTINGDATABASE

      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME

      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-vars-secret
            key: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD

    dbSslCaCrtSecret: internal-ca-secret
    dbSslAdminCrtSecret: postgres-cluster-client-cert
    dbSslUserCrtSecret: postgres-cluster-client-cert
