name: hashicorp-vault
repoURL: https://helm.releases.hashicorp.com
targetRevision: 0.30.0
chart: vault
namespace: infra
values: |
  fullnameOverride: hashicorp-vault
  server:
    enabled: true
    dev:
      enabled: false  # PRODUÇÃO: dev=false
    extraEnvironmentVars:
      VAULT_UI: "true"
    ha:
      enabled: true
      raft:
        enabled: true
        config: |
          ui = true
          storage "raft" {
            path    = "/vault/data"
            node_id = "vault-0"
          }
          listener "tcp" {
            address     = "0.0.0.0:8200"
            tls_disable = 1
          }
          service_registration "kubernetes" {}
    readinessProbe:
      enabled: true
    livenessProbe:
      enabled: true
  extraVolumes:
    - name: vault-tls
      secret:
        secretName: vault-tls
  extraVolumeMounts:
    - name: vault-tls
      mountPath: /vault/tls
      readOnly: true
  ui:
    enabled: true

